pub mod index;
pub mod routine;
pub mod table;
pub mod types;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::write::execute;
use super::{Call, Outcome, Route};
use crate::error::{Error, Result};
use crate::render::{QualifiedName, verify};

#[derive(Debug, Default)]
pub struct Missing {
    fields: Vec<String>,
}

impl Missing {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    pub fn need(&mut self, field: &str, present: bool) -> &mut Self {
        if !present {
            self.fields.push(field.to_owned());
        }
        self
    }

    pub fn finish(&self, operation: &str) -> Result<()> {
        if self.fields.is_empty() {
            return Ok(());
        }
        Err(Error::ArgumentInvalid {
            argument: self.fields.join(", "),
            detail: format!(
                "the {operation} operation needs {}: {}",
                if self.fields.len() == 1 {
                    "this field"
                } else {
                    "these fields"
                },
                self.fields.join(", ")
            ),
        })
    }
}

pub fn scoped_name(call: &Call, kind: &str, name: &str) -> Result<QualifiedName> {
    QualifiedName::parse(kind, name, &call.settings().schema.value)
}

#[must_use]
pub const fn if_exists_clause(if_exists: bool) -> &'static str {
    if if_exists { " IF EXISTS" } else { "" }
}

#[must_use]
pub const fn if_not_exists_clause(if_not_exists: bool) -> &'static str {
    if if_not_exists { " IF NOT EXISTS" } else { "" }
}

#[must_use]
pub const fn cascade_suffix(cascade: bool) -> &'static str {
    if cascade { " CASCADE" } else { "" }
}

pub async fn run_ddl(
    call: &Call,
    tool: &str,
    sql: String,
    expected_kinds: &[&str],
    dry_run: bool,
    confirm: bool,
    transaction: &str,
) -> Outcome {
    let classification = verify(&sql, expected_kinds)?;
    execute(
        call,
        tool,
        &sql,
        &classification,
        dry_run,
        confirm,
        transaction,
    )
    .await
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Toggle {
    #[default]
    Unset,
    On,
    Off,
}

impl Toggle {
    #[must_use]
    pub const fn as_bool(self) -> Option<bool> {
        match self {
            Self::Unset => None,
            Self::On => Some(true),
            Self::Off => Some(false),
        }
    }
}

pub fn number(field: &str, text: &str) -> Result<Option<i64>> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }
    trimmed
        .parse::<i64>()
        .map(Some)
        .map_err(|_| Error::ArgumentInvalid {
            argument: field.to_owned(),
            detail: format!("`{trimmed}` is not a whole number"),
        })
}

pub fn decimal(field: &str, text: &str) -> Result<Option<f64>> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }
    trimmed
        .parse::<f64>()
        .ok()
        .filter(|value| value.is_finite())
        .map(Some)
        .ok_or_else(|| Error::ArgumentInvalid {
            argument: field.to_owned(),
            detail: format!("`{trimmed}` is not a number"),
        })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ReferentialAction {
    #[default]
    Unset,
    NoAction,
    Restrict,
    Cascade,
    SetNull,
    SetDefault,
}

impl ReferentialAction {
    #[must_use]
    pub const fn sql(self) -> &'static str {
        match self {
            Self::Unset | Self::NoAction => "NO ACTION",
            Self::Restrict => "RESTRICT",
            Self::Cascade => "CASCADE",
            Self::SetNull => "SET NULL",
            Self::SetDefault => "SET DEFAULT",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Identity {
    #[default]
    None,
    Always,
    ByDefault,
}

impl Identity {
    #[must_use]
    pub const fn sql(self) -> &'static str {
        match self {
            Self::None => "",
            Self::Always => "GENERATED ALWAYS AS IDENTITY",
            Self::ByDefault => "GENERATED BY DEFAULT AS IDENTITY",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedKind {
    #[default]
    Stored,
    Virtual,
}

pub fn routes() -> Result<Vec<Route>> {
    let mut routes = table::routes()?;
    routes.extend(index::routes()?);
    routes.extend(routine::routes()?);
    routes.extend(types::routes()?);
    Ok(routes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn toggles_and_numbers_parse() {
        assert_eq!(Toggle::Unset.as_bool(), None);
        assert_eq!(Toggle::On.as_bool(), Some(true));
        assert_eq!(number("start", " 10 ").unwrap(), Some(10));
        assert_eq!(number("start", "").unwrap(), None);
        assert!(number("start", "ten").is_err());
        assert_eq!(decimal("cost", "1.5").unwrap(), Some(1.5));
        assert!(decimal("cost", "inf").is_err());
    }

    #[test]
    fn every_missing_field_is_named_at_once() {
        let mut missing = Missing::new();
        missing
            .need("new_type", false)
            .need("using", true)
            .need("column", false);
        let error = missing.finish("alter_type").unwrap_err();
        let text = error.to_string();
        assert!(text.contains("new_type"));
        assert!(text.contains("column"));
        assert!(!text.contains("using"));
        assert!(Missing::new().finish("x").is_ok());
    }
}
